### ISSUE TITLE
Script is unable to download zip files

### ISSUE THREAD

**Issue by jbellmann** [juliangruendner/pj7-data-extraction#1]
Hello,

we tried to use this project to setup some data for testing purposes. Unfortunately step 1 `get-mii-testdata.sh` fails. The script is not able to download the zip files. That's because the zip files do not exist anymore. Only some references to git-lfs.github.com exist and `wget` can not resolve them.
Any ideas on how to proceed?
Will the scripts now use git and git-lfs?
Or someone informs the provider of these [Test_Data](https://github.com/medizininformatik-initiative/kerndatensatz-testdaten)?

**Comment by juliangruendner** [comment]
@jbellmann: i have now loaded the testdata into this repository directly - this is a workaround until the lfs issues in the other repository are resolved
