### ISSUE TITLE
bug: index out of range

### ISSUE THREAD

**Issue by Mehrsary** [juliangruendner/pj7-data-extraction#2]
[build-transaction-bundle.py#74](https://github.com/juliangruendner/pj7-data-extraction/blob/d414f7749b8fc51ae14ebea9b9c03dcfe33ba385/build-transaction-bundle.py#L77) returns index error since entry is there but is an empty array.

For example check here: https://mii-agiop-3p.life.uni-leipzig.de/blaze/DocumentReference?identifier=http://medizininformatik-initiative.de/sid/project-identifier|NT-proBNP

```mii-data-extraction_1  | Begin creation of extraction transfer bundle...
mii-data-extraction_1  | Traceback (most recent call last):
mii-data-extraction_1  |   File "/opt/data-extraction/build-transaction-bundle.py", line 79, in <module>
mii-data-extraction_1  |     existing_doc_ref_id = get_existing_doc_ref("NT-proBNP")
mii-data-extraction_1  |   File "/opt/data-extraction/build-transaction-bundle.py", line 74, in get_existing_doc_ref
mii-data-extraction_1  |     return resp_json["entry"][0]["resource"]["id"]
mii-data-extraction_1  | IndexError: list index out of range```

**Comment by juliangruendner** [comment]
@Mehrsary : I fixed this - however it seems that u are running an older version of blaze - in the newest version "entry" should not appear at all in the response
