### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by florisa** [juliangruendner/pj7-data-extraction#7]
**We are getting the following error while running the container with real data:**

_It was tested before with test data and it was fine.
We are using blaze 0.18.4 and Ubuntu 20.04, file and folder permissions all checked._

_Here the log, thanks in advance!_

Starting mii-projectathon_mii-data-extraction_1 ... done
Attaching to mii-projectathon_mii-data-extraction_1
mii-data-extraction_1  | Begin extracting data at time 2023-02-13_15-49-08...
mii-data-extraction_1  | Extracting data for obs...
mii-data-extraction_1  | Extracted 44 resources for extraction with name obs
mii-data-extraction_1  | Extracting data for pats...
mii-data-extraction_1  | Extracted 20 resources for extraction with name pats
mii-data-extraction_1  | Extracting data for enc...
mii-data-extraction_1  | Extracted 301 resources for extraction with name enc
mii-data-extraction_1  | Extracting data for cond...
mii-data-extraction_1  | Extracted 1188 resources for extraction with name cond
mii-data-extraction_1  | Finished extracting data
mii-data-extraction_1  | Begin pseudonymising data...
mii-data-extraction_1  | Begin pseudonymisation of: extracted_resources/obs.json...
mii-data-extraction_1  | Finished pseudonymisation of: extracted_resources/obs.json
mii-data-extraction_1  | Begin pseudonymisation of: extracted_resources/pats.json...
mii-data-extraction_1  | Finished pseudonymisation of: extracted_resources/pats.json
mii-data-extraction_1  | Begin pseudonymisation of: extracted_resources/enc.json...
mii-data-extraction_1  | Traceback (most recent call last):
mii-data-extraction_1  |   File "/opt/data-extraction/pseudonymisation.py", line 369, in <module>
mii-data-extraction_1  |     psd_list = pseudonomise_resources(input_list, psd_config)
mii-data-extraction_1  |   File "/opt/data-extraction/pseudonymisation.py", line 342, in pseudonomise_resources
mii-data-extraction_1  |     psd_resources.append(pseudonomise_resource(resource, psd_config))
mii-data-extraction_1  |   File "/opt/data-extraction/pseudonymisation.py", line 317, in pseudonomise_resource
mii-data-extraction_1  |     change_id_in_obj_by_expression_simple(
mii-data-extraction_1  |   File "/opt/data-extraction/pseudonymisation.py", line 145, in change_id_in_obj_by_expression_simple
mii-data-extraction_1  |     change_id_in_obj_by_expression_simple(path, id_change, resource)
mii-data-extraction_1  |   File "/opt/data-extraction/pseudonymisation.py", line 138, in change_id_in_obj_by_expression_simple
mii-data-extraction_1  |     change_id_in_obj_by_expression_simple(path, id_change, arr_entry)
mii-data-extraction_1  |   File "/opt/data-extraction/pseudonymisation.py", line 113, in change_id_in_obj_by_expression_simple
mii-data-extraction_1  |     cur_key = path.pop(0)
mii-data-extraction_1  | IndexError: pop from empty list
mii-data-extraction_1  | Finished pseudonymising data
mii-data-extraction_1  | Begin creation of extraction transfer bundle...
mii-data-extraction_1  | Traceback (most recent call last):
mii-data-extraction_1  |   File "/opt/data-extraction/build-transaction-bundle.py", line 86, in <module>
mii-data-extraction_1  |     with open(f'pseudonymised_resources/{res_name}_{psd_date_time}.json', 'r') as f:
mii-data-extraction_1  | FileNotFoundError: [Errno 2] No such file or directory: 'pseudonymised_resources/cond_2023-02-13_15-49-08.json'
mii-data-extraction_1  | Finished creation of extraction transfer bundle...
mii-data-extraction_1  | Goodbye - have a nice day
mii-projectathon_mii-data-extraction_1 exited with code 0

**Comment by juliangruendner** [comment]
@florisa  - please use the newest version of this repository instead: https://github.com/medizininformatik-initiative/Projectathon7-VHF-DataExtraction
